# Create a null vector of size 10 but the fifth value which is 1.

In [1]:
import numpy as np 
(np.arange(10)==4).astype(int)

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

# Create a 3x3 matrix with values ranging from 0 to 8


In [3]:
x=np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# Create a vector with values ranging from 10 to 49.

In [4]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

# Find indices of non-zero elements from [1,2,0,0,4,0]

In [8]:
x=np.array([1,2,0,0,4,0])
print("indices of non-zero elements are:",np.nonzero(x))

indices of non-zero elements are: (array([0, 1, 4], dtype=int64),)


# Create a 10x10 array with random values and find the minimum and maximum values.

In [12]:
# import random
random.seed(10)
x=np.random.random(size=(10,10))
print("Minimum vales:",x.min())
print("Maximum values:",x.max())
print(x)

Minimum vales: 0.0011815132616231905
Maximum values: 0.9869919040435984
[[0.28565662 0.81836024 0.52309563 0.83401772 0.9400339  0.20575618
  0.14020792 0.61089122 0.46415979 0.21619318]
 [0.41741477 0.48625445 0.46771967 0.04496279 0.4438119  0.1561554
  0.79923028 0.83532946 0.36439595 0.51391058]
 [0.7910099  0.89300165 0.0683352  0.3555846  0.48202802 0.3200311
  0.50597725 0.98426259 0.89014955 0.00118151]
 [0.01461379 0.65657694 0.93546228 0.68458836 0.69769316 0.98167002
  0.69854323 0.04741607 0.39884421 0.70111501]
 [0.67747339 0.87314664 0.58509456 0.94332239 0.9869919  0.67276716
  0.21596437 0.34250687 0.95302955 0.24096445]
 [0.80494458 0.79648177 0.7246619  0.74608498 0.93199122 0.44789323
  0.28929231 0.08797782 0.58232986 0.29646442]
 [0.91694295 0.31411952 0.83531481 0.38964898 0.23287062 0.37933601
  0.13381337 0.89100312 0.10582613 0.90869013]
 [0.58591153 0.62804052 0.22817883 0.37855781 0.94478368 0.33735644
  0.61552231 0.31258606 0.75668292 0.44896582]
 [0.692235

# Create a random vector of size 30 and find the mean value.

In [11]:
arr=np.random.random((5,6))
Mean_value_of_the_matrix=np.mean(arr)
print("mean:",Mean_value_of_the_matrix)

mean: 0.5354088028177687
